# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-26 08:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=128, unique=True, verbose_name='工单编号')),
                ('titel', models.CharField(max_length=64, verbose_name='工单标题')),
                ('problem_type', models.SmallIntegerField(choices=[(0, '门户'), (1, 'CS')], default=0, verbose_name='问题分类')),
                ('dev_people', models.CharField(blank=True, max_length=32, null=True, verbose_name='研发处理人')),
                ('resolvents', models.SmallIntegerField(choices=[(0, '临时解决'), (1, '最终解决')], default=0, verbose_name='解决方案')),
                ('resolvent', models.CharField(blank=True, max_length=128, null=True, verbose_name='解决方法')),
                ('status', models.SmallIntegerField(choices=[(0, '未进行'), (1, '进行中'), (2, '已完成')], default=1, verbose_name='状态')),
                ('transfer', models.CharField(blank=True, max_length=64, null=True, verbose_name='工单移交')),
                ('timeout', models.BooleanField(default=False, verbose_name='超时')),
                ('timeout_cause', models.CharField(blank=True, max_length=128, null=True, verbose_name='超时原因')),
                ('resolventplan', models.CharField(blank=True, max_length=64, null=True, verbose_name='处理计划')),
                ('nextresolvent', models.CharField(blank=True, max_length=128, null=True, verbose_name='进一步解决方案')),
                ('testing_job', models.CharField(blank=True, max_length=128, null=True, verbose_name='测试对接任务')),
                ('dev_job', models.CharField(blank=True, max_length=128, null=True, verbose_name='开发对接任务')),
                ('estimate_time', models.DateTimeField(blank=True, null=True, verbose_name='预计解决时间')),
                ('refailure', models.BooleanField(verbose_name='复发故障')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('resolve_time', models.DateTimeField(blank=True, null=True, verbose_name='最终解决时间')),
                ('ops_people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to=settings.AUTH_USER_MODEL, verbose_name='运维处理人')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='名称')),
            ],
            options={
                'verbose_name': '资源池',
                'verbose_name_plural': '资源池',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='csops.Pool', verbose_name='资源池'),
        ),
    ]
