# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-26 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='problem',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='问题描述'),
        ),
    ]
