# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-27 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csops', '0003_auto_20181227_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='timeout',
            field=models.BooleanField(choices=[(0, 'False'), (1, 'True')], verbose_name='超时'),
        ),
    ]
