# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-27 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csops', '0002_job_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='problem',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='分析原因'),
        ),
        migrations.AlterField(
            model_name='job',
            name='timeout',
            field=models.BooleanField(choices=[(0, 'False'), (1, 'True')], default=0, verbose_name='超时'),
        ),
    ]
