# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-29 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csops', '0002_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '部门', 'verbose_name_plural': '部门'},
        ),
        migrations.AlterField(
            model_name='job',
            name='problem_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='csops.Department', verbose_name='问题分类'),
        ),
    ]
