# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-29 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csops', '0003_auto_20181229_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='problem_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='csops.Department', verbose_name='问题分类'),
        ),
    ]
