# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-21 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csops', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='csops.Job', verbose_name='工单'),
        ),
    ]
