# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-29 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csops', '0004_auto_20181229_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='problem_type',
            field=models.SmallIntegerField(choices=[(0, '门户'), (1, 'CS')], default=0, verbose_name='问题分类'),
        ),
    ]
